/**
 * @graphmemory/browser-client — a tiny, dependency-free client for the
 * browser-mcp stateless REST API (`/api/v1`).
 *
 * Stateless: every call is an independent POST. `profile` selects which shared
 * live browser to drive (the same profile an MCP agent uses); pass `tab_id` in
 * args to target a specific tab. Node 18+ (uses the global `fetch`).
 *
 * Tool argument types come from the server's OpenAPI spec via `openapi-typescript`
 * (see `src/generated/openapi.ts`, regenerated by `npm run gen`).
 */

import type { operations } from "./generated/openapi.js";

/** Every tool name from the OpenAPI spec (operationId == tool name). */
export type ToolName = keyof operations;

/** Argument shape for a given tool, derived from its OpenAPI requestBody. */
export type ToolArgs<N extends ToolName> =
  operations[N] extends { requestBody?: { content: { "application/json": infer A } } }
    ? A
    : Record<string, never>;

/** A content block (text, or base64 image for screenshots), mirrored from MCP. */
export type ContentBlock =
  | { type: "text"; text: string }
  | { type: "image"; data: string; mimeType: string };

/** The JSON envelope every tool call resolves to. `ok:false` is a tool-level
 *  failure (e.g. a failed assertion) — still an HTTP 200. */
export type ToolEnvelope<T = unknown> =
  | { ok: true; data?: T; content: ContentBlock[] }
  | { ok: false; error: { message: string; issues?: unknown }; data?: T; content?: ContentBlock[] };

/** Thrown on a transport-layer failure (4xx/5xx): bad args, auth, unknown tool, cap. */
export class BrowserClientError extends Error {
  readonly status: number;
  readonly body: unknown;
  constructor(message: string, status: number, body: unknown) {
    super(message);
    this.name = "BrowserClientError";
    this.status = status;
    this.body = body;
  }
}

export interface BrowserClientOptions {
  /** Base URL of the browser-mcp server, e.g. "http://127.0.0.1:7777". */
  baseUrl: string;
  /** Bearer token, required only if the server was started with an API key. */
  apiKey?: string;
  /** Default profile (shared browser) to target. Defaults to "default". */
  profile?: string;
  /** Override fetch (for tests or custom agents). Defaults to the global fetch. */
  fetch?: typeof fetch;
}

type CallOpts = { profile?: string };

// If ToolArgs<N> is empty (no fields), allow callers to omit the args entirely.
type ArgsParam<N extends ToolName> = Record<string, never> extends ToolArgs<N>
  ? [args?: ToolArgs<N>, opts?: CallOpts]
  : [args: ToolArgs<N>, opts?: CallOpts];

export class BrowserClient {
  private readonly baseUrl: string;
  private readonly apiKey?: string;
  private readonly profile: string;
  private readonly _fetch: typeof fetch;

  constructor(opts: BrowserClientOptions) {
    this.baseUrl = opts.baseUrl.replace(/\/+$/, "");
    this.apiKey = opts.apiKey;
    this.profile = opts.profile ?? "default";
    this._fetch = opts.fetch ?? globalThis.fetch;
  }

  private headers(json: boolean): Record<string, string> {
    const h: Record<string, string> = {};
    if (json) h["content-type"] = "application/json";
    if (this.apiKey) h["authorization"] = `Bearer ${this.apiKey}`;
    return h;
  }

  private async toJson(res: Response): Promise<unknown> {
    return res.json().catch(() => ({}));
  }

  /**
   * Call any tool by name. Arguments are type-checked against the OpenAPI
   * spec. Resolves with the 200 envelope (`ok` may be `false` for a tool-level
   * failure); throws BrowserClientError on a transport error (4xx/5xx).
   */
  async tool<N extends ToolName>(name: N, ...rest: ArgsParam<N>): Promise<ToolEnvelope> {
    const [args, opts] = rest;
    const profile = opts?.profile ?? this.profile;
    const url = `${this.baseUrl}/api/v1/tools/${encodeURIComponent(name)}?profile=${encodeURIComponent(profile)}`;
    const res = await this._fetch(url, {
      method: "POST",
      headers: this.headers(true),
      body: JSON.stringify(args ?? {}),
    });
    const body = await this.toJson(res);
    if (!res.ok) {
      const message = (body as { error?: { message?: string } })?.error?.message ?? `HTTP ${res.status}`;
      throw new BrowserClientError(message, res.status, body);
    }
    return body as ToolEnvelope;
  }

  /** List the available tools (names + descriptions). */
  async listTools(): Promise<{ tools: Array<{ name: string; description: string }> }> {
    const res = await this._fetch(`${this.baseUrl}/api/v1/tools`, { headers: this.headers(false) });
    if (!res.ok) throw new BrowserClientError(`HTTP ${res.status}`, res.status, await this.toJson(res));
    return res.json() as Promise<{ tools: Array<{ name: string; description: string }> }>;
  }

  /** Fetch the OpenAPI 3.1 document describing the API. */
  async openapi(): Promise<unknown> {
    const res = await this._fetch(`${this.baseUrl}/api/v1/openapi.json`, { headers: this.headers(false) });
    if (!res.ok) throw new BrowserClientError(`HTTP ${res.status}`, res.status, await this.toJson(res));
    return res.json();
  }

  /** Release a profile holder (closes its browser if no MCP session holds it). */
  async releaseProfile(profile: string = this.profile): Promise<{ ok: boolean; released: boolean }> {
    const res = await this._fetch(`${this.baseUrl}/api/v1/profiles/${encodeURIComponent(profile)}`, {
      method: "DELETE",
      headers: this.headers(false),
    });
    if (!res.ok) throw new BrowserClientError(`HTTP ${res.status}`, res.status, await this.toJson(res));
    return res.json() as Promise<{ ok: boolean; released: boolean }>;
  }

  // --- ergonomic shortcuts for common tools (types derived from the spec) ---

  open(url: string, opts: Omit<ToolArgs<"browser_open">, "url"> & CallOpts = {}) {
    const { profile, ...args } = opts;
    return this.tool("browser_open", { url, ...args } as ToolArgs<"browser_open">, { profile });
  }

  read(opts: ToolArgs<"browser_read"> & CallOpts = {}) {
    const { profile, ...args } = opts;
    return this.tool("browser_read", args as ToolArgs<"browser_read">, { profile });
  }

  click(target: string, opts: Omit<ToolArgs<"browser_click">, "target"> & CallOpts = {}) {
    const { profile, ...args } = opts;
    return this.tool("browser_click", { target, ...args } as ToolArgs<"browser_click">, { profile });
  }

  type(target: string, text: string, opts: Omit<ToolArgs<"browser_type">, "target" | "text"> & CallOpts = {}) {
    const { profile, ...args } = opts;
    return this.tool("browser_type", { target, text, ...args } as ToolArgs<"browser_type">, { profile });
  }

  snapshot(opts: ToolArgs<"browser_snapshot"> & CallOpts = {}) {
    const { profile, ...args } = opts;
    return this.tool("browser_snapshot", args as ToolArgs<"browser_snapshot">, { profile });
  }

  evaluate(expression: string, opts: Omit<ToolArgs<"browser_evaluate">, "expression"> & CallOpts = {}) {
    const { profile, ...args } = opts;
    return this.tool("browser_evaluate", { expression, ...args } as ToolArgs<"browser_evaluate">, { profile });
  }

  tabsList(opts: CallOpts = {}) {
    return this.tool("browser_tabs_list", {}, opts);
  }
}
